import {forward,cloneWeights,backward,sgd,loss} from './engine.js';
import {$,$$,f,pct,heatmap,color,esc} from './render.js';
import {STEPS,renderLesson} from './lessons.js';
import {GUIDE} from './guide.js';
const state={step:1,channel:0,inputChannel:0,x:13,y:13,index:0,neuron:0,classIndex:7,target:7,rate:.01,snapshot:'trained',sampleIndex:0,source:'sample',scanning:false,trainingSteps:0,trainingHistory:[]};
let timer=null,drawContext=null,drawing=false,lastPoint=null,drawFrame=null;
const app={state,
  lesson(){const element=document.activeElement;const active=element?.id?'#'+element.id:['data-channel','data-neuron','data-index','data-slice'].filter(k=>element?.hasAttribute(k)).map(k=>`[${k}="${element.getAttribute(k)}"]`)[0];const opened=$$('#lesson details[open]').map(d=>d.querySelector('summary')?.textContent);renderLesson(app);$$('#lesson details').forEach(d=>{if(opened.includes(d.querySelector('summary')?.textContent))d.open=true;});if(active&&$(active))$(active).focus({preventScroll:true});paintInput();},
  focus(x,y){state.x=x;state.y=y;this.lesson();},
  channel(c){state.channel=c;this.lesson();},
  setStep(index,scroll=false){const fromNav=document.activeElement?.closest('#stage-nav');if(!Number.isInteger(index)||index<0||index>=STEPS.length)throw new Error('Invalid lesson');this.stopScan();state.step=index;state.x=Math.min(state.x,index>=3?index===3?13:6:27);state.y=Math.min(state.y,index>=3?index===3?13:6:27);renderNav();renderNetwork();this.lesson();const selected=$('.stage-button.selected');if(fromNav)selected.focus({preventScroll:true});const nav=$('#stage-nav');nav.scrollTo({left:Math.max(0,selected.offsetLeft-nav.offsetLeft-nav.clientWidth/2+selected.clientWidth/2),behavior:motion()});if(scroll)$('#explorer-title').scrollIntoView({behavior:motion()});$('#announcement').textContent=`Step ${index+1}: ${STEPS[index].title}`;},
  stopScan(){clearInterval(timer);timer=null;state.scanning=false;},
  scan(n){if(state.scanning){this.stopScan();this.lesson();return;}state.scanning=true;this.lesson();timer=setInterval(()=>{const i=(state.y*n+state.x+1)%(n*n);state.x=i%n;state.y=Math.floor(i/n);this.lesson();},250);},
  update(){state.tensors=forward(state.pixels,state.weights);renderPrediction();renderNetwork();this.lesson();},
  resetTraining(){state.trainingHistory=[];state.lastUpdate=null;},
  loadSample(index){this.stopScan();state.sampleIndex=index;state.source='sample';const sample=state.samples[index];state.pixels=Float64Array.from(sample.pixels,p=>p/255);state.target=sample.label;state.classIndex=sample.label;this.resetTraining();renderInputControls();this.update();},
  setSnapshot(snapshot){if(!['trained','initial'].includes(snapshot))throw new Error('Invalid snapshot');this.stopScan();state.snapshot=snapshot;state.weights=cloneWeights(state.model[snapshot]);state.trainingSteps=0;this.resetTraining();updateModelControls();this.update();},
  trainingStep(){const grads=backward(state.tensors,state.weights,state.target);if(!state.trainingHistory.length)state.trainingHistory.push(grads.loss);const index=grads.weights.conv1Weight.reduce((best,v,i)=>Math.abs(v)>Math.abs(grads.weights.conv1Weight[best])?i:best,0);state.lastUpdate={index,before:state.weights.conv1Weight[index],gradient:grads.weights.conv1Weight[index],rate:state.rate};state.weights=sgd(state.weights,grads.weights,state.rate);state.trainingSteps++;this.update();state.trainingHistory.push(loss(state.tensors.logits,state.target));updateModelControls();this.lesson();},
  editPixel(index,value){state.pixels[index]=value;state.source='edited';this.resetTraining();renderInputControls();this.update();},
  gradient(){return backward(state.tensors,state.weights,state.target);}
};
function motion(){return matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth';}
function updateModelControls(){const trained=state.snapshot==='trained';$('#trained').classList.toggle('selected',trained);$('#trained').setAttribute('aria-pressed',trained);$('#untrained').classList.toggle('selected',!trained);$('#untrained').setAttribute('aria-pressed',!trained);$('#accuracy').textContent=state.trainingSteps?`${state.trainingSteps} local weight update${state.trainingSteps===1?'':'s'}`:trained?`${pct(state.model.meta.history.at(-1).accuracy)} test accuracy`:'Random initialization';}
function renderInputControls(){const sample=state.samples[state.sampleIndex],isSample=state.source==='sample';$('#input-canvas').hidden=state.source==='draw';$('#draw-canvas').hidden=state.source!=='draw';$('#sample-controls').hidden=!isSample;$('#draw-controls').hidden=state.source!=='draw';$('#sample-mode').classList.toggle('selected',isSample);$('#sample-mode').setAttribute('aria-pressed',isSample);$('#draw-mode').classList.toggle('selected',state.source==='draw');$('#draw-mode').setAttribute('aria-pressed',state.source==='draw');$('.digit-picker').innerHTML=Array.from({length:10},(_,i)=>`<button data-digit="${i}" class="${sample.label===i?'selected':''}" aria-label="Load a sample of digit ${i}" aria-pressed="${sample.label===i}">${i}</button>`).join('');$$('[data-digit]').forEach(b=>b.onclick=()=>app.loadSample(state.samples.findIndex(s=>s.label===Number(b.dataset.digit))));$('#sample-label').textContent=`Test #${sample.id}`;$('#input-note').textContent=state.source==='sample'?'784 pixels. One grayscale channel.':state.source==='draw'?'Your drawing stays on this device.':'Your image stays on this device.';}
function paintInput(){if(!state.pixels)return;heatmap($('#input-canvas'),state.pixels,28,{gray:true,...(state.step===1?{x:state.x,y:state.y,patch:true}:{})});}
function renderPrediction(){const probs=state.tensors.softmax,winner=Array.from(probs).indexOf(Math.max(...probs));$('#predicted-digit').textContent=winner;$('#prediction-percent').textContent=pct(probs[winner]);$('#probabilities').innerHTML=Array.from(probs,(p,i)=>`<button class="probability ${i===winner?'winner':''} ${i===state.classIndex?'selected':''}" data-class="${i}" aria-label="Inspect digit ${i}, probability ${pct(p)}"><span class="prob-label">${i}</span><span class="prob-track"><span class="prob-fill" style="display:block;width:${p*100}%"></span></span><span class="prob-value">${pct(p)}</span></button>`).join('');$$('[data-class]').forEach(b=>b.onclick=()=>{state.classIndex=Number(b.dataset.class);app.setStep(10,true);});const blank=state.pixels.every(p=>p===0);$('#prediction-note').textContent=blank?'Blank input · draw or choose a digit.':state.snapshot==='initial'&&!state.trainingSteps?'Untrained network · scores are not learned.':state.source==='sample'?`True label: ${state.samples[state.sampleIndex].label} · ${winner===state.samples[state.sampleIndex].label?'Correct prediction':'A real model mistake'}`:'Custom digit · the model may be uncertain or wrong.';}
function neuralSvg(output=false){const n=output?10:8;let lines='',nodes='';for(let i=0;i<6;i++)for(let j=0;j<n;j++)lines+=`<line x1="20" y1="${14+i*18}" x2="78" y2="${8+j*104/(n-1)}" stroke="#b9a1ff" opacity="${.07+(i+j)%4*.02}"/>`;for(let i=0;i<6;i++)nodes+=`<circle cx="20" cy="${14+i*18}" r="4" fill="#172336" stroke="#9c82d9" stroke-width="1"/>`;for(let j=0;j<n;j++){const v=output?state.tensors.softmax[j]:Math.min(1,state.tensors.hidden[j*16]/3);nodes+=`<circle cx="78" cy="${8+j*104/(n-1)}" r="${output?4:5}" fill="${color(v,1)}" stroke="${output?'#65dfca':'#b9a1ff'}" stroke-width="1"/>`;}return `<svg class="node-svg" viewBox="0 0 100 120" aria-hidden="true">${lines}${nodes}</svg>`;}
function renderNetwork(){const block=state.step<=3?1:state.step<=7?4:state.step===8?8:10;$('#network-flow').innerHTML=`<button class="network-block ${block===1?'selected':''}" data-step="1" aria-label="Explore the first convolution block"><div class="tensor-stack">${[0,1,2].map(i=>`<canvas data-map="pool1" data-ch="${i}" aria-hidden="true"></canvas>`).join('')}</div><span class="net-name">Conv block 1</span><span class="net-shape">8 × 14 × 14</span><span class="net-op">Conv → ReLU → Pool</span></button><span class="net-arrow" aria-hidden="true">→</span><button class="network-block ${block===4?'selected':''}" data-step="4" aria-label="Explore the second convolution block"><div class="tensor-stack smaller">${[2,6,9].map(i=>`<canvas data-map="pool2" data-ch="${i}" aria-hidden="true"></canvas>`).join('')}</div><span class="net-name">Conv block 2</span><span class="net-shape">16 × 7 × 7</span><span class="net-op">Conv → ReLU → Pool</span></button><span class="net-arrow" aria-hidden="true">→</span><button class="network-block classification ${block===8?'selected':''}" data-step="8" aria-label="Explore the fully connected layer">${neuralSvg()}<span class="net-name">Dense</span><span class="net-shape">784 → 128</span><span class="net-op">Linear → ReLU</span></button><span class="net-arrow" aria-hidden="true">→</span><button class="network-block classification ${block===10?'selected':''}" data-step="10" aria-label="Explore the output probabilities">${neuralSvg(true)}<span class="net-name">Output</span><span class="net-shape">128 → 10</span><span class="net-op">Linear → Softmax</span></button>`;$$('#network-flow [data-step]').forEach(b=>b.onclick=()=>app.setStep(Number(b.dataset.step),true));$$('[data-map]').forEach(c=>{const n=c.dataset.map==='pool1'?14:7,ch=Number(c.dataset.ch);heatmap(c,state.tensors[c.dataset.map].slice(ch*n*n,(ch+1)*n*n),n);});$('#network-note-copy').textContent=state.step>=8?'Every output neuron connects to all 128 hidden activations. The diagram shows a subset of the hidden neurons; inspect the full weight tables below.':'The first block detects local strokes. The second combines them across eight channels. The stacks preview three channels; inspect every channel below.';}
function renderNav(){$('#stage-nav').innerHTML=STEPS.map((s,i)=>`<button class="stage-button ${state.step===i?'selected':''}" data-lesson="${i}" ${state.step===i?'aria-current="step"':''}><span>${String(i+1).padStart(2,'0')}</span>${s.label}</button>`).join('');$$('[data-lesson]').forEach(b=>b.onclick=()=>app.setStep(Number(b.dataset.lesson)));$('#step-count').textContent=`${String(state.step+1).padStart(2,'0')} / 12`;$('#previous-step').disabled=state.step===0;$('#next-step').disabled=state.step===11;}
function beginDrawing(){app.stopScan();state.source='draw';app.resetTraining();renderInputControls();drawContext=$('#draw-canvas').getContext('2d');drawContext.fillStyle='#000';drawContext.fillRect(0,0,280,280);state.pixels=new Float64Array(784);app.update();}
function updateDrawing(){const mini=document.createElement('canvas');mini.width=mini.height=28;const c=mini.getContext('2d',{willReadFrequently:true});c.drawImage($('#draw-canvas'),0,0,28,28);const rgba=c.getImageData(0,0,28,28).data;state.pixels=Float64Array.from({length:784},(_,i)=>rgba[4*i]/255);app.resetTraining();app.update();}
function drawPoint(e){const canvas=$('#draw-canvas'),r=canvas.getBoundingClientRect(),p=[(e.clientX-r.left)*280/r.width,(e.clientY-r.top)*280/r.height];drawContext.strokeStyle='#fff';drawContext.fillStyle='#fff';drawContext.lineWidth=19;drawContext.lineCap='round';drawContext.lineJoin='round';drawContext.beginPath();if(lastPoint){drawContext.moveTo(...lastPoint);drawContext.lineTo(...p);drawContext.stroke();}else{drawContext.arc(...p,9.5,0,Math.PI*2);drawContext.fill();}lastPoint=p;if(!drawFrame)drawFrame=requestAnimationFrame(()=>{drawFrame=null;updateDrawing();});}
function fitCanvas(source){const c=source.getContext('2d',{willReadFrequently:true}),{data}=c.getImageData(0,0,source.width,source.height);let x0=source.width,y0=source.height,x1=-1,y1=-1;for(let y=0;y<source.height;y++)for(let x=0;x<source.width;x++){if(data[(y*source.width+x)*4]>25){x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);}}const output=document.createElement('canvas');output.width=output.height=280;const ctx=output.getContext('2d');ctx.fillStyle='#000';ctx.fillRect(0,0,280,280);if(x1>=x0){const w=x1-x0+1,h=y1-y0+1,scale=200/Math.max(w,h);ctx.drawImage(source,x0,y0,w,h,(280-w*scale)/2,(280-h*scale)/2,w*scale,h*scale);}return output;}
function wireDrawing(){const canvas=$('#draw-canvas');canvas.onpointerdown=e=>{if(state.source!=='draw')return;e.preventDefault();canvas.setPointerCapture(e.pointerId);drawing=true;lastPoint=null;drawPoint(e);};canvas.onpointermove=e=>{if(drawing)drawPoint(e);};const end=()=>{drawing=false;lastPoint=null;};canvas.onpointerup=end;canvas.onpointercancel=end;canvas.onlostpointercapture=end;$('#clear-drawing').onclick=beginDrawing;$('#use-drawing').onclick=()=>{drawContext.drawImage(fitCanvas(canvas),0,0);updateDrawing();};$('#upload-image').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>15*1024*1024)throw new Error('Choose an image smaller than 15 MB.');const bitmap=await createImageBitmap(file);const source=document.createElement('canvas');source.width=source.height=280;const c=source.getContext('2d',{willReadFrequently:true});c.fillStyle='#fff';c.fillRect(0,0,280,280);const scale=Math.min(280/bitmap.width,280/bitmap.height);c.drawImage(bitmap,(280-bitmap.width*scale)/2,(280-bitmap.height*scale)/2,bitmap.width*scale,bitmap.height*scale);bitmap.close();const pixels=c.getImageData(0,0,280,280);let border=0,count=0;for(let y=0;y<280;y++)for(let x=0;x<280;x++)if(x<5||y<5||x>274||y>274){const i=(y*280+x)*4;border+=(pixels.data[i]+pixels.data[i+1]+pixels.data[i+2])/3;count++;}const invert=border/count>127;for(let i=0;i<pixels.data.length;i+=4){let v=.299*pixels.data[i]+.587*pixels.data[i+1]+.114*pixels.data[i+2];if(invert)v=255-v;pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=v;pixels.data[i+3]=255;}c.putImageData(pixels,0,0);beginDrawing();drawContext.drawImage(fitCanvas(source),0,0);updateDrawing();state.source='upload';renderInputControls();paintInput();renderPrediction();$('#upload-status').textContent='Image loaded and centered. Select Learning to set its correct label.';}catch(error){$('#upload-status').textContent=error.message||'This image could not be decoded. Try PNG or JPEG.';}};}
function webMCP(){const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const tools=[{name:'inspect_cnn',description:'Read the current CNN input, layer, prediction, and real class scores.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({layer:STEPS[state.step].id,source:state.source,model:state.snapshot,probabilities:Array.from(state.tensors.softmax),logits:Array.from(state.tensors.logits)})},{name:'explore_cnn_sample',description:'Load an MNIST test digit and navigate to a CNN lesson in the visible lab.',inputSchema:{type:'object',properties:{digit:{type:'integer',minimum:0,maximum:9},step:{type:'integer',minimum:0,maximum:11}},required:['digit','step'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!Number.isInteger(input?.digit)||input.digit<0||input.digit>9||!Number.isInteger(input?.step)||input.step<0||input.step>11)throw new Error('Expected digit 0–9 and step 0–11.');app.loadSample(state.samples.findIndex(s=>s.label===input.digit));app.setStep(input.step,true);return {layer:STEPS[state.step].id,probabilities:Array.from(state.tensors.softmax)};}}];for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{ /* Optional browser capability; the visual lab remains usable. */ }}}
async function init(){try{const responses=await Promise.all(['./assets/model.json','./assets/samples.json'].map(url=>fetch(url)));if(responses.some(r=>!r.ok))throw new Error('The model files could not be loaded. Reload the page or try again shortly.');[state.model,state.samples]=await Promise.all(responses.map(r=>r.json()));state.weights=cloneWeights(state.model.trained);app.loadSample(state.samples.findIndex(s=>s.label===7));updateModelControls();renderNav();$('#lab').hidden=false;$('#loading').hidden=true;$('#trained').onclick=()=>app.setSnapshot('trained');$('#untrained').onclick=()=>app.setSnapshot('initial');$('#sample-mode').onclick=()=>app.loadSample(state.sampleIndex);$('#draw-mode').onclick=beginDrawing;$('#next-sample').onclick=()=>{const label=state.samples[state.sampleIndex].label,indices=state.samples.map((s,i)=>s.label===label?i:-1).filter(i=>i>=0);app.loadSample(indices[(indices.indexOf(state.sampleIndex)+1)%indices.length]);};$('#previous-step').onclick=()=>app.setStep(state.step-1);$('#next-step').onclick=()=>app.setStep(state.step+1);$('#start-tour').onclick=()=>app.setStep(0,true);wireDrawing();webMCP();$('#guide-content').innerHTML=GUIDE.map(([title,body])=>`<details><summary>${title}</summary><p>${body}</p></details>`).join('');const meta=state.model.meta;$('#model-facts').innerHTML=[['Architecture','1 → 8 → 16 channels'],['Classifier','784 → 128 → 10'],['Training',`${meta.epochs} epochs · Adam`],['Exported test accuracy',`${pct(meta.history.at(-1).accuracy)} / 10,000 images`],['Dataset','MNIST · 60,000 training digits'],['Execution','100% in your browser']].map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('');}catch(error){$('#loading').hidden=true;$('#load-error').hidden=false;$('#load-error').innerHTML=`${esc(error.message)} <button class="button" onclick="location.reload()">Retry</button>`;$('#start-tour').disabled=true;$('#trained').disabled=true;$('#untrained').disabled=true;}}
init();
