import { signLegend, signedRGB, inkOn } from './palette.js';
import { renderTrainingMovie } from './training-player.js';
import { renderWorkedConvolution, enhanceDense, renderWorkedSoftmax, enhanceRelu, enhancePooling } from './math-views.js';
import {convolutionCell} from './engine.js';
import {$,$$,f,pct,color,heatmap,mapEvents,matrix,options} from './render.js';
export const STEPS=[
  {id:'input',label:'Input',title:'An image is a matrix.',description:'A computer does not start with a “seven.” It starts with 784 numbers. Each number records how bright one pixel is, from 0 (black) to 1 (white).',code:'ToTensor()\nx = pixel / 255',shape:'1 × 28 × 28'},
  {id:'conv1',label:'Conv 1',title:'A filter looks for a pattern.',description:'Slide a small 3 × 3 grid of learned weights across the image. At each position, multiply matching values, add the nine products, and add a bias. One calculation becomes one pixel in a feature map.',code:'Conv2d(1, 8, 3, padding=1)',shape:'1 × 28 × 28 → 8 × 28 × 28'},
  {id:'relu1',label:'ReLU',title:'Keep the positive signal.',description:'ReLU changes every negative activation to zero and leaves positive values alone. This simple bend lets the network learn relationships that a stack of linear operations cannot.',code:'a = max(0, z)',shape:'8 × 28 × 28 → 8 × 28 × 28'},
  {id:'pool1',label:'Pool 1',title:'Keep the strongest response.',description:'Divide each feature map into non-overlapping 2 × 2 windows. Keep only the largest value in each window. The result is half as wide and half as tall, retaining a compact summary of local responses.',code:'MaxPool2d(kernel_size=2)',shape:'8 × 28 × 28 → 8 × 14 × 14'},
  {id:'conv2',label:'Conv 2',title:'Combine patterns across channels.',description:'The second convolution sees all eight feature maps at once. Each of its 16 filters contains eight separate 3 × 3 slices. Add the eight slice responses and one bias to get a single output value.',code:'Conv2d(8, 16, 3, padding=1)',shape:'8 × 14 × 14 → 16 × 14 × 14'},
  {id:'relu2',label:'ReLU',title:'Another nonlinear decision.',description:'The second convolution mixes the first block’s features. ReLU again removes negative responses. The same rule now acts on 16 channels containing more contextual patterns.',code:'a₂ = max(0, z₂)',shape:'16 × 14 × 14 → 16 × 14 × 14'},
  {id:'pool2',label:'Pool 2',title:'Condense the evidence.',description:'A second 2 × 2 max-pool compresses the 16 feature maps into 7 × 7 grids. Each surviving number summarizes a region of earlier activity. The channel count stays the same.',code:'MaxPool2d(kernel_size=2)',shape:'16 × 14 × 14 → 16 × 7 × 7'},
  {id:'flatten',label:'Flatten',title:'Same numbers. One long vector.',description:'Flattening changes how the values are arranged, not what they are. Read each 7 × 7 map row by row, then move to the next channel. All 16 maps become a vector of 784 features.',code:'Flatten()\nindex = channel × 49 + row × 7 + col',shape:'16 × 7 × 7 → 784'},
  {id:'dense',label:'Dense',title:'Connect all the evidence.',description:'Each of 128 neurons gets all 784 features. It multiplies each feature by its own weight, adds all 784 contributions and a bias, then applies ReLU. Select a neuron to inspect its exact calculation.',code:'Linear(784, 128) → ReLU()',shape:'784 → 128'},
  {id:'logits',label:'Logits',title:'Ten scores. No probabilities yet.',description:'The last linear layer connects the 128 hidden activations to ten output neurons, one per digit. A score can be positive or negative. The largest score is the predicted class.',code:'Linear(128, 10)\nz = W × h + b',shape:'128 → 10'},
  {id:'softmax',label:'Softmax',title:'Turn scores into a distribution.',description:'Exponentiate the ten logits and divide each result by their sum. The probabilities add to one. Subtracting the largest logit before exponentiating keeps the calculation numerically stable.',code:'pᵢ = exp(zᵢ − m) / Σ exp(zⱼ − m)\nm = max(z)',shape:'10 logits → 10 probabilities'},
  {id:'learn',label:'Learning',title:'How does the network learn?',description:'Compare the prediction with the correct label, calculate how each weight affected the error, then nudge the weights. This sandbox runs real backpropagation through every layer for the current image.',code:'loss = −log(p[correct digit])\nw ← w − learning_rate × ∂loss/∂w',shape:'Prediction → loss → gradients → weights'}
];
export function renderLesson(app) {
  const s=app.state,step=STEPS[s.step];
  if(step.id==='learn'){renderTrainingMovie(app);return;}
  $('#lesson').innerHTML=`<div class="lesson-top"><div class="lesson-copy"><p class="eyebrow">STEP ${String(s.step+1).padStart(2,'0')} / ${s.step<7?'FEATURE EXTRACTION':s.step===11?'LEARNING':'CLASSIFICATION'}</p><h3>${step.title}</h3><p>${step.description}</p><code class="code-label">${step.code}</code><div class="shape-line"><strong>${step.shape}</strong></div></div><div class="lesson-work" id="lesson-work"></div></div><div id="feature-strip"></div>`;
  if(step.id==='conv1'||step.id==='conv2') renderConv(app);
  else if(step.id==='input') renderInput(app);
  else if(step.id.startsWith('relu')) renderRelu(app);
  else if(step.id.startsWith('pool')) renderPool(app);
  else if(step.id==='flatten') renderFlatten(app);
  else if(step.id==='dense'||step.id==='logits') renderDense(app);
  else if(step.id==='softmax') renderSoftmax(app);
  if (step.id === 'conv1' || step.id === 'conv2') renderWorkedConvolution(app);
  else if (step.id === 'dense' || step.id === 'logits') enhanceDense(app);
  else if (step.id === 'softmax') renderWorkedSoftmax(app);
  else if (step.id.startsWith('relu')) enhanceRelu(app);
  else if (step.id.startsWith('pool')) enhancePooling(app);
}
function renderConv(app) {
  const s=app.state,layer=s.step===1?1:2,n=layer===1?28:14,channels=layer===1?8:16;
  s.channel=Math.min(s.channel,channels-1);s.x=Math.min(s.x,n-1);s.y=Math.min(s.y,n-1);
  const input=s.tensors[layer===1?'input':'pool1'],output=s.tensors[`conv${layer}`];
  const calc=convolutionCell(input,s.weights,layer,s.channel,s.y,s.x),slice=calc.slices[layer===1?0:s.inputChannel];
  $('#lesson-work').innerHTML=`<div class="work-toolbar"><h4>The math at <span class="mono">[${s.y}, ${s.x}]</span></h4><div class="controls"><label>Filter <select id="filter-select">${options(channels,s.channel)}</select></label>${layer===2?`<label>Input channel <select id="input-channel">${options(8,s.inputChannel)}</select></label>`:''}<button id="scan-kernel" class="button">${s.scanning?'Ⅱ Pause':'▷ Slide filter'}</button></div></div><div class="map-and-math"><div class="map-column"><div class="map-label"><span>Output feature map</span><span class="mono">${n} × ${n}</span></div><canvas id="feature-focus" class="heatmap-large" aria-label="Select a convolution output cell. Use arrow keys to move."></canvas><p class="map-caption">Click a cell or use arrow keys. ${signLegend()}</p><div class="map-coordinates"><label>Row <input id="row-input" type="number" min="0" max="${n-1}" value="${s.y}"></label><label>Col <input id="col-input" type="number" min="0" max="${n-1}" value="${s.x}"></label></div></div><div><div class="math-expression"><em>z</em> = Σ (input × weight) + bias</div><div class="matrix-equation">${matrix(slice.patch,'INPUT PATCH',{padding:slice.padding})}<span class="math-op">⊙</span>${matrix(slice.kernel,'FILTER WEIGHTS')}<span class="math-op">=</span>${matrix(slice.products,'9 PRODUCTS')}</div>${layer===2?`<div class="channel-sums">${calc.slices.map((v,i)=>`<button data-slice="${i}" class="${i===s.inputChannel?'selected':''}" aria-pressed="${i===s.inputChannel}">ch ${i}: ${f(v.sum,3)}</button>`).join('')}</div>`:''}<div class="sum-line"><span>${layer===1?'Σ products':'Σ 8 channels'} <b>${f(calc.total-calc.bias,4)}</b></span><span>+ bias ${f(calc.bias,4)}</span><span>=</span><strong class="sum-value">${f(calc.total,4)}</strong></div><p class="math-note">${layer===1?'The same nine weights are reused at every position. Eight filters create eight different feature maps.':'Each chip is the sum of nine products in one input channel. All eight chips contribute to the output; the bias is added once.'} Values shown are rounded; the calculation uses full precision.</p></div></div>`;
  heatmap($('#feature-focus'),output.slice(s.channel*n*n,(s.channel+1)*n*n),n,{x:s.x,y:s.y});
  mapEvents($('#feature-focus'),n,(x,y)=>app.focus(x,y));
  $('#filter-select').onchange=e=>app.channel(Number(e.target.value));
  if(layer===2)$('#input-channel').onchange=e=>{s.inputChannel=Number(e.target.value);app.lesson();};
  $$('[data-slice]').forEach(b=>b.onclick=()=>{s.inputChannel=Number(b.dataset.slice);app.lesson();});
  $('#row-input').onchange=e=>app.focus(s.x,Math.max(0,Math.min(n-1,Math.trunc(Number(e.target.value)||0))));
  $('#col-input').onchange=e=>app.focus(Math.max(0,Math.min(n-1,Math.trunc(Number(e.target.value)||0))),s.y);
  $('#scan-kernel').onclick=()=>app.scan(n);
  renderStrip(app,`conv${layer}`,channels,n);
}
export function renderStrip(app,key,channels,n) {
  const s=app.state;
  $('#feature-strip').innerHTML=`<div class="feature-strip"><div class="strip-label"><strong>All ${channels} channels</strong><span>Select a feature map</span></div><div class="feature-maps">${Array.from({length:channels},(_,i)=>`<button class="feature-map ${i===s.channel?'selected':''}" data-channel="${i}" aria-label="Inspect channel ${i}" aria-pressed="${i===s.channel}"><canvas aria-hidden="true"></canvas><span>${String(i).padStart(2,'0')}</span></button>`).join('')}</div></div>`;
  $$('[data-channel]').forEach(b=>{const i=Number(b.dataset.channel);heatmap($('canvas',b),s.tensors[key].slice(i*n*n,(i+1)*n*n),n);b.onclick=()=>app.channel(i);});
}
function coordinateControls(s,n) {return `<div class="map-coordinates"><label>Row <input id="row-input" type="number" min="0" max="${n-1}" value="${s.y}"></label><label>Col <input id="col-input" type="number" min="0" max="${n-1}" value="${s.x}"></label></div>`;}
function wireCoordinates(app,n) {
  const s=app.state;
  $('#row-input').onchange=e=>app.focus(s.x,Math.max(0,Math.min(n-1,Math.trunc(Number(e.target.value)||0))));
  $('#col-input').onchange=e=>app.focus(Math.max(0,Math.min(n-1,Math.trunc(Number(e.target.value)||0))),s.y);
}
function renderInput(app) {
  const s=app.state,n=28,index=s.y*n+s.x,v=s.pixels[index],byte=Math.round(v*255);
  $('#lesson-work').innerHTML=`<div class="work-toolbar"><h4>Inspect or change any pixel</h4><span class="mono subtle">1 channel · 784 values</span></div><div class="map-and-math"><div class="map-column"><div class="map-label"><span>Input tensor</span><span class="mono">28 × 28</span></div><canvas id="pixel-map" class="heatmap-large" aria-label="Input pixel inspector. Click a pixel or move with arrow keys."></canvas><p class="map-caption">Click a pixel or use arrow keys to inspect it.</p>${coordinateControls(s,n)}</div><div><div class="math-expression">x[0, ${s.y}, ${s.x}] = <em>${byte} / 255 = ${f(v,5)}</em></div><div class="pixel-swatch" style="background:${color(v,1,true)}"></div><div class="controls"><label for="pixel-value">Pixel brightness <input id="pixel-value" type="range" min="0" max="255" value="${byte}"> <span class="mono">${byte}</span></label></div><p class="math-note">Change this pixel and watch the prediction update. This is the same data path used by drawing a digit. A pixel near a stroke can affect many overlapping convolution windows.</p><div class="value-callout"><span class="subtle">Shape </span><strong>[1, 28, 28]</strong><br><span class="subtle small">channel, row, column · zero-based indices</span></div></div></div>`;
  heatmap($('#pixel-map'),s.pixels,n,{gray:true,x:s.x,y:s.y});mapEvents($('#pixel-map'),n,(x,y)=>app.focus(x,y));wireCoordinates(app,n);
  $('#pixel-value').onchange=e=>app.editPixel(index,Number(e.target.value)/255);
}
function renderRelu(app) {
  const s=app.state,layer=s.step===2?1:2,n=layer===1?28:14,channels=layer===1?8:16;
  s.channel=Math.min(s.channel,channels-1);s.x=Math.min(s.x,n-1);s.y=Math.min(s.y,n-1);
  const key=`conv${layer}`,outputKey=`relu${layer}`,offset=s.channel*n*n,index=offset+s.y*n+s.x,before=s.tensors[key][index],after=s.tensors[outputKey][index];
  const negatives=s.tensors[key].slice(offset,offset+n*n).filter(v=>v<0).length;
  $('#lesson-work').innerHTML=`<div class="work-toolbar"><h4>${negatives} of ${n*n} responses set to zero</h4><div class="controls"><label>Channel <select id="relu-channel">${options(channels,s.channel)}</select></label><button class="button" id="find-negative" ${negatives===0?'disabled':''}>Find a negative</button></div></div><div class="two-map"><div><p class="map-label">Before ReLU · signed</p><canvas id="relu-before" class="heatmap-large" aria-label="Select an activation before ReLU"></canvas></div><span class="transform-arrow" aria-hidden="true">→</span><div><p class="map-label">After ReLU · nonnegative</p><canvas id="relu-after" class="heatmap-large" aria-label="Select an activation after ReLU"></canvas></div></div><div class="value-callout">a[${s.channel}, ${s.y}, ${s.x}] = max(0, ${f(before,4)}) = <strong>${f(after,4)}</strong></div><p class="math-note">${before<0?'This negative response is blocked. The derivative through this ReLU is 0.':before>0?'This positive response passes through unchanged. The derivative through this ReLU is 1.':'At exactly zero, this implementation uses derivative 0, matching PyTorch.'} Colors are scaled independently in each map; compare numeric values above.</p>`;
  for(const [id,tensor] of [['#relu-before',key],['#relu-after',outputKey]]){heatmap($(id),s.tensors[tensor].slice(offset,offset+n*n),n,{x:s.x,y:s.y});mapEvents($(id),n,(x,y)=>app.focus(x,y));}
  $('#relu-channel').onchange=e=>app.channel(Number(e.target.value));$('#find-negative').onclick=()=>{const i=s.tensors[key].slice(offset,offset+n*n).findIndex(v=>v<0);if(i>=0)app.focus(i%n,Math.floor(i/n));};renderStrip(app,outputKey,channels,n);
}
function renderPool(app) {
  const s=app.state,layer=s.step===3?1:2,n=layer===1?28:14,out=n/2,channels=layer===1?8:16;
  s.channel=Math.min(s.channel,channels-1);s.x=Math.min(s.x,out-1);s.y=Math.min(s.y,out-1);
  const input=s.tensors[`relu${layer}`],output=s.tensors[`pool${layer}`],start=s.channel*n*n+2*s.y*n+2*s.x;
  const indices=[start,start+1,start+n,start+n+1],patch=indices.map(i=>input[i]),max=Math.max(...patch),winner=patch.indexOf(max);
  $('#lesson-work').innerHTML=`<div class="work-toolbar"><h4>A 2 × 2 window becomes one number</h4><div class="controls"><label>Channel <select id="pool-channel">${options(channels,s.channel)}</select></label><span class="mono subtle">window 2 · stride 2</span></div></div><div class="map-and-math"><div class="map-column"><div class="map-label"><span>Pooled output</span><span class="mono">${out} × ${out}</span></div><canvas id="pool-output" class="heatmap-large" aria-label="Select a pooled output to inspect its input window"></canvas><p class="map-caption">Select a cell to see the four values that produced it.</p>${coordinateControls(s,out)}</div><div><div class="pool-window-equation"><div><p class="matrix-title">SOURCE ACTIVATIONS</p><canvas id="pool-source" class="heatmap-large" role="img" aria-label="Input feature map with the selected two by two pooling window highlighted"></canvas></div><span class="math-op">→</span>${matrix(patch,'SELECTED WINDOW',{maxIndex:winner})}</div><div class="value-callout">max(${patch.map(v=>f(v,2)).join(', ')}) = <strong>${f(max,4)}</strong></div><p class="math-note">The outlined value wins. During backpropagation, only this location receives the window’s gradient. Ties go to the first maximum in row-major order.</p></div></div>`;
  heatmap($('#pool-output'),output.slice(s.channel*out*out,(s.channel+1)*out*out),out,{x:s.x,y:s.y});mapEvents($('#pool-output'),out,(x,y)=>app.focus(x,y));wireCoordinates(app,out);
  heatmap($('#pool-source'),input.slice(s.channel*n*n,(s.channel+1)*n*n),n,{x:2*s.x,y:2*s.y,region:2});$('#pool-channel').onchange=e=>app.channel(Number(e.target.value));renderStrip(app,`pool${layer}`,channels,out);
}
function renderFlatten(app) {
  const s=app.state;s.index=Math.max(0,Math.min(783,s.index));
  const channel=Math.floor(s.index/49),row=Math.floor(s.index%49/7),col=s.index%7,max=Math.max(...s.tensors.flatten);
  $('#lesson-work').innerHTML=`<div class="work-toolbar"><h4>All 784 features, in channel-first order</h4><div class="controls"><label>Index <input id="flat-index" type="number" min="0" max="783" value="${s.index}"></label></div></div><div class="flat-vector" aria-label="Flattened feature values">${Array.from(s.tensors.flatten,(v,i)=>`<button class="${i===s.index?'selected':''}" data-index="${i}" aria-label="Feature ${i}: ${f(v,5)}" style="background:${color(v,max)}" title="index ${i}: ${v}"></button>`).join('')}</div><div class="value-callout">flat[<strong>${s.index}</strong>] = pool₂[${channel}, ${row}, ${col}] = <strong>${f(s.tensors.flatten[s.index],5)}</strong></div><p class="math-note">${channel} × 49 + ${row} × 7 + ${col} = ${s.index}. Each tiny square is one real activation. The squares wrap to fit your screen; that wrapping is only a display choice.</p><div class="flatten-origin"><canvas id="flatten-origin" role="img" aria-label="Source feature map for the selected flattened value"></canvas><p>Channel <strong>${channel}</strong>, row <strong>${row}</strong>, column <strong>${col}</strong><br><span class="subtle">The highlighted cell is copied directly into this vector position.</span></p></div>`;
  $$('[data-index]').forEach(b=>b.onclick=()=>{s.index=Number(b.dataset.index);app.lesson();});$('#flat-index').onchange=e=>{s.index=Math.max(0,Math.min(783,Math.trunc(Number(e.target.value)||0)));app.lesson();};
  heatmap($('#flatten-origin'),s.tensors.pool2.slice(channel*49,(channel+1)*49),7,{x:col,y:row});
}
function renderDense(app) {
  const s=app.state,isLogit=s.step===9,n=isLogit?128:784,count=isLogit?10:128,out=isLogit?s.classIndex:s.neuron;
  const input=s.tensors[isLogit?'hidden':'flatten'],weight=s.weights[isLogit?'fc2Weight':'fc1Weight'],bias=s.weights[isLogit?'fc2Bias':'fc1Bias'][out],pre=s.tensors[isLogit?'logits':'dense'][out],post=isLogit?pre:s.tensors.hidden[out];
  const contributions=Array.from(input,(v,i)=>({i,x:v,w:weight[out*n+i],product:v*weight[out*n+i]})).sort((a,b)=>Math.abs(b.product)-Math.abs(a.product));
  const max=Math.max(...s.tensors.hidden);
  $('#lesson-work').innerHTML=`<div class="work-toolbar"><h4>${isLogit?'Output class':'Hidden neuron'} ${out}</h4><div class="controls"><label>${isLogit?'Digit':'Neuron'} <select id="dense-neuron">${options(count,out)}</select></label></div></div>${isLogit?`<div class="chart-bars">${Array.from(s.tensors.logits,(v,i)=>`<div class="logit-column ${i===out?'winner':''}"><span class="bar-value">${f(v,2)}</span><div class="logit-bar" style="height:${20+(v-Math.min(...s.tensors.logits))/(Math.max(...s.tensors.logits)-Math.min(...s.tensors.logits)||1)*125}px"></div><span class="bar-label">${i}</span></div>`).join('')}</div><p class="map-caption">Bars use a shifted display scale. Read the labels for signed logit values.</p>`:`<div class="dense-grid" role="group" aria-label="All 128 hidden neurons">${Array.from(s.tensors.hidden,(v,i)=>`<button data-neuron="${i}" class="${i===out?'selected':''}" style="background:${color(v,max)};color:${inkOn(signedRGB(v,max))}" title="Neuron ${i} · activation ${v}" aria-label="Inspect neuron ${i}, activation ${f(v,4)}">${i}</button>`).join('')}</div>`}<div class="math-expression">z[${out}] = Σ<sub>i=0…${n-1}</sub> x[i] × W[${out}, i] + b[${out}]</div><div class="sum-line"><span>Σ contributions ${f(pre-bias,5)}</span><span>+ ${f(bias,5)}</span><span>=</span><strong class="sum-value">${f(pre,5)}</strong>${isLogit?'':`<span>→ ReLU → <strong>${f(post,5)}</strong></span>`}</div><p class="math-note">All ${n} connections, sorted by the size of their contribution. Positive products push this score up; negative products pull it down. Zero inputs contribute zero regardless of their weight.</p><div class="table-scroll" tabindex="0" aria-label="All connection values for the selected neuron"><table class="contribution-table"><thead><tr><th>Input index</th><th>Activation</th><th>Weight</th><th>Product</th></tr></thead><tbody>${contributions.map(v=>`<tr><td>${v.i}</td><td>${f(v.x,5)}</td><td>${f(v.w,5)}</td><td>${f(v.product,5)}</td></tr>`).join('')}</tbody></table></div>`;
  $('#dense-neuron').onchange=e=>{if(isLogit)s.classIndex=Number(e.target.value);else s.neuron=Number(e.target.value);app.lesson();};$$('[data-neuron]').forEach(b=>b.onclick=()=>{s.neuron=Number(b.dataset.neuron);app.lesson();});
}
function renderSoftmax(app) {
  const s=app.state,z=s.tensors.logits,p=s.tensors.softmax,m=Math.max(...z),e=Array.from(z,v=>Math.exp(v-m)),sum=e.reduce((a,b)=>a+b,0),i=s.classIndex;
  $('#lesson-work').innerHTML=`<div class="work-toolbar"><h4>Every step from logits to probabilities</h4><div class="controls"><label>Digit <select id="softmax-class">${options(10,i)}</select></label></div></div><div class="math-expression">p[${i}] = exp(${f(z[i],3)} − ${f(m,3)}) / ${f(sum,5)}</div><div class="value-callout">${f(e[i],7)} / ${f(sum,7)} = <strong>${pct(p[i])}</strong></div><div class="table-scroll softmax-table"><table class="contribution-table"><thead><tr><th>Digit</th><th>Logit z</th><th>exp(z − max)</th><th>Probability</th></tr></thead><tbody>${Array.from(z,(v,j)=>`<tr ${j===i?'class="highlight-row"':''}><td>${j}</td><td>${f(v,5)}</td><td>${e[j]<.00001?e[j].toExponential(3):f(e[j],6)}</td><td>${pct(p[j])}</td></tr>`).join('')}</tbody><tfoot><tr><td>Sum</td><td>—</td><td>${f(sum,6)}</td><td>100%</td></tr></tfoot></table></div><p class="math-note">Subtract the same maximum (${f(m,4)}) from every logit, exponentiate, then divide by the sum. Small values may display as zero when rounded; they still participate in the full-precision calculation.</p>`;
  $('#softmax-class').onchange=ev=>{s.classIndex=Number(ev.target.value);app.lesson();};
}
